### PR TITLE
Fixing a bug for the querystring as the querystring returned from URL.Query() could be reordered

### PR DESCRIPTION
**Pull request by nickveenhof**
Fixing a bug for the querystring as the querystring returned from URL.Query() could be reordered

### CODE REVIEW

**Comment by baliame** [comment]
Will have to test this with Plexus before it is merged.

**Comment by nickveenhof** [comment]
Obviously, but it is a bug in the go code, so if this breaks plexus it means the specification wasn't adhering to the specification. I'll wait on your confirmation before merging :)

I could write a test for it perhaps

**Comment by mccarthy** [comment]
I tested this accidentally for my search needs, and it worked well.  I didn't test without it - so I can't say whether I would have hit the issue or not.

**Comment by nickveenhof** [comment]
@baliame, it's becoming a little pressing. Can you please add it to your next sprint or take a moment to review?

**Comment by baliame** [comment]
Actually, this is my bad, I completely forgot, and I'll deal with the fallout on the plexus side if there's any.

**Pull request merged**
